name: Build desktop executable
on:
  push:
    branches:
      - main
      - enable_ga_for_build
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Upload macos artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-dist
          path: build/dist
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        run: |
          chmod +x build.sh
          bash build.sh
      - name: Upload windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-dist
          path: build/dist